project:
  type: testproject
  pre-render: copy-extension.ts

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



